# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyuD2vcr2urBd7uhg9xqoMccFzBS6qBB
"""

!pip install dash pandas plotly jupyter-dash

import pandas as pd

# 데이터프레임 생성
data = {
    "start_time": ["8:00", "9:00", "10:00"],
    "start_station": ["Station A", "Station B", "Station A"],
    "end_station": ["Station B", "Station C", "Station C"],
    "transport_mode": ["Ladybug", "Foot", "Ladybug"],
    "total_duration": [5, 15, 10],
    "distance": [1500, 500, 2000],
}
df = pd.DataFrame(data)

from jupyter_dash import JupyterDash
from dash import dcc, html, dash_table
import plotly.express as px

# 애플리케이션 생성
app = JupyterDash(__name__)

# 시각화 1: 원형 차트
pie_chart = px.pie(df, names="transport_mode", title="이동 수단 비율")

# 시각화 2: 선형 그래프
line_chart = px.line(df, x="start_time", y="distance", title="시간대별 이동 거리", markers=True)

# 시각화 3: 막대 그래프
bar_chart = px.bar(df, x="transport_mode", y="distance", title="이동 수단별 평균 거리")

# 데이터 테이블
data_table = dash_table.DataTable(
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict('records'),
)

# 레이아웃 구성
app.layout = html.Div([
    html.H1("무당이 대시보드", style={'textAlign': 'center'}),
    dcc.Graph(figure=pie_chart),
    dcc.Graph(figure=line_chart),
    dcc.Graph(figure=bar_chart),
    data_table
])

# 대시보드 실행
app.run_server(mode="inline")

